# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27f4b038908e4916d85a10814c8a90d947c5965930b129c1a40ee2d2fb0973071bac3ddb9a08ebcb8b757fda455ee67f9ddb927f6e0b891de07be1f4ca0d5994

test:
  secret_key_base: 2950cf1dd4fc800b776936d45b524ce0be62c2bdb2bf223c1582421d63b20b449c0908ec3de00b786db986268558a242db611f80753481a786021307201c1b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
