Rails.application.routes.draw do

  # route to a form for creating a new high_score
  get 'high_scores/new', to: 'high_scores#new', as: 'new_high_score'

  # route to editing an existing high_score
  get 'high_scores/:id/edit', to: 'high_scores#edit', as: 'edit_high_score'

  # route to view an individual HighScore object
  get 'high_scores/:id', to: 'high_scores#show', as: 'high_score'

  # route to view all HighScore objects
  get 'high_scores', to: 'high_scores#index', as: 'high_scores'

  # after form generated by new is filled out and submit is clicked
  #   a post verb is sent. Now we have the info to actually create the
  #   object requested
  post 'high_scores', to: 'high_scores#create'

  # after form generated by edit is filled out and submit is clicked
  #   a patch verb is sent. Now we have the info from the form to edit
  #   the object
  patch 'high_scores/:id', to: 'high_scores#update'

  # route to delete a specific object
  delete 'high_scores/:id', to: 'high_scores#destroy'

  # route to index(landing page)
  root "high_scores#index"

end
