# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b53705a859787404ad8958dcd2c3ff0d4f12c2c1993d207b6d619cc9e13d04c1d5d6b231939080799c80f3bb91378e5d338ae9d60b7002f3d197c79bd7a434c

test:
  secret_key_base: e74cfffa69629b481d0ba8590d7738cfa2ec282f8f41e542c7293bd859e286eb3ac1a609ef17bb08fbf4a74e4c81c709bf43f385d3e48ba663f03a11eb3bba80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
